/*
OASIS INFOBYTE

 Intern Name : Bommagoni Prashanth

 * Task Number : 02
 
 * Task Name : Number Guessing Game(NGG)
 
 * Task Description :

The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:
The system generates a random number from a given range, say 1 to 100.
The user is prompted to enter their given number in a displayed dialogue box.
The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
The game continues under the user guessing the number.

You can also incorporate further details as:

Limiting the number of attempts.

Adding more rounds.

Displaying score.

Giving points based on the number of attempts.

*/

//Source Code: 
import java.util.Scanner;
import java.util.Random;

public class numberGuessingGame{
    public static void main(String args[]){
        Random random=new Random();
        Scanner input=new Scanner(System.in);
        int numberOfAttempts = 1;
        int numberOfGuess;
        int score = 0;
        int guessedNumber = random.nextInt(100);
        System.out.println("|**** WELCOME TO THE NUMBER GUESSING GAME ****| \n");
        System.out.println("You have only 10 attempts to guess the number right!\n");
        System.out.println("Rules for Scoring:\n");
        System.out.println("1.For every unsuccessful attempt your score will get deducted by 1 point\n");
        System.out.println("2.For successful attempt you will get 10 points\n");
        System.out.println("Guess a number between 1 and 100:\n");
        while(true)
        {
            if(input.hasNextInt())
            {
                numberOfGuess=input.nextInt();
                if(numberOfGuess == guessedNumber)
                {
                    score+=10;
                    System.out.println("Congo!! You Won The Game.");
                    System.out.println("Your score is "+score+" and you guessed it in "+numberOfAttempts+" attempts");
                    break;
                } else if (numberOfGuess < guessedNumber) {
                    System.out.println("Your guess is too small!!!");
                    System.out.println("Attempts remaining = "+(10 - numberOfAttempts));
                    score--;
                } else if (numberOfGuess > guessedNumber) {
                    System.out.println("Your guess is too big!!!");
                    System.out.println("Attempts remaining = "+(10 - numberOfAttempts));
                    score--;
                }
                if(numberOfAttempts == 10)
                {
                    System.out.println("Sorry! You have exceeded the maximum number of attempts!");
                    System.out.println("Better Luck Next Time!!");
                    break;
                }
                numberOfAttempts++;
            }
            else {
                System.out.println("Please enter a valid number!");
                break;
            }
        }
        input.close();
    }
}